server:
  port: 8765

spring:
  application:
    name: gateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      server:
        webflux:

          # âœ… CORS for Gateway (WebFlux)
          globalcors:
            corsConfigurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:3000"
                  - "http://localhost:4200"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - PATCH
                  - OPTIONS
                allowedHeaders:
                  - "*"
                allowCredentials: true

          routes:
            # 1) Prefix route: /HOSPITALMANGEMENTAPI/** -> forwards to service without the prefix
            - id: CMS_PREFIX
              uri: lb://CMS
              predicates:
                - Path=/CMS/**
              filters:
                - StripPrefix=1


            # 2) Direct route: no prefix, forward as-is
            - id: CMS_DIRECT
              uri: lb://CMS
              predicates:
                - Path=/swagger-ui.html,/v3/api-docs/**,/swagger-ui/**,/users/**,/roles/**
            # 1) Prefix route: /HOSPITALMANGEMENTAPI/** -> forwards to service without the prefix
            - id: USERPROFILE_PREFIX
              uri: lb://USERPROFILE
              predicates:
                - Path=/USERPROFILE/**
              filters:
                - StripPrefix=2


            # 2) Direct route: no prefix, forward as-is
            - id: USERPROFILE_DIRECT
              uri: lb://USERPROFILE
              predicates:
                - Path=/swagger-ui.html,/v3/api-docs/**,/swagger-ui/**,/users/**,/roles/**

            - id: ADDRESS-VALIDATION-SERVICE_PREFIX
              uri: lb://ADDRESS-VALIDATION-SERVICE
              predicates:
                - Path=/ADDRESS-VALIDATION-SERVICE/**
              filters:
                - StripPrefix=1


              # 2) Direct route: no prefix, forward as-is
            - id: ADDRESS-VALIDATION-SERVICE_DIRECT
              uri: lb://ADDRESS-VALIDATION-SERVICE
              predicates:
                - Path=/swagger-ui.html,/v3/api-docs/**,/swagger-ui/**,/users/**,/roles/**
              # 1) Prefix route: /HOSPITALMANGEMENTAPI/** -> forwards to service without the prefix
            - id: AUDIT-SERVICE_PREFIX
              uri: lb://AUDIT-SERVICE
              predicates:
                - Path=/AUDIT-SERVICE/**
              filters:
                - StripPrefix=2


            # 2) Direct route: no prefix, forward as-is
            - id: AUDIT-SERVICE_DIRECT
              uri: lb://AUDIT-SERVICE
              predicates:
                - Path=/swagger-ui.html,/v3/api-docs/**,/swagger-ui/**,/users/**,/roles/**


          discovery:
            locator:
              enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
